### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#145]
There are currently several test suites, each approaching testing from a different POV. The outputs of child issues will be added as guidelines to our wiki.

Within this issue, I would like to:
1. Document what is currently covered.
2. Create issues for missing coverage based on findings from #144 
3. Consider different structure or approach (what is mocked) for unit vs integration vs E2E tests.
4. Consider other quality processes and practices (Storybook, FE testing) for both CLI and Portal.
5. Kick off best practices/guidelines for writing tests.

Child issues:
- #157 
- #263 
- #277 
- #276
- #264

**Comment by kristihoskova** [comment]
Time-box for this spike is 1MD and after that we will decide what's next.

**Comment by BioPhoton** [comment]
consider helper functions for file reads in utils

**Comment by BioPhoton** [comment]
Write helper for the inner logic to share
```typescript
vi.mock('@code-pushup/portal-client', async () => {
  const module: typeof import('@code-pushup/portal-client') =
    await vi.importActual('@code-pushup/portal-client');

  return {
    ...module,
    uploadToPortal: vi.fn(
      async () => ({ packageName: '@code-pushup/cli' } as ReportFragment),
    ),
  };
});
```

**Comment by BioPhoton** [comment]
Is there a open PR for this?

**Comment by BioPhoton** [comment]
I like the order of the issues! ❤️

**Comment by Tlacenka** [comment]
The testing strategy principles can be found [here](https://github.com/code-pushup/cli/wiki/Testing-Strategy).
