### ISSUE TITLE
Inform user about invalid arguments

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#163]
As a user, I wish to receive an error message when I enter an invalid argument. Currently, CLI ignores invalid options.

**Comment by BioPhoton** [comment]
I suggest we just list the passed arguments. We should not throw an error as our CLI could get overloaded or executed with other processes and shared global options.  e.g. `nx affected -t test build --testNamePatter=blub` is not throwing even if build does not support the `--testNamePatter` option.

**Comment by kristihoskova** [comment]
The solution for this issue is already implemented
