### ISSUE TITLE
Sorting audits in stdout and MD format

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#210]
As a CLI only user, I want to make sense of my text output. Currently, I have to skim through the whole list of audits as they are not ordered in any obvious way.

This ordering could be inspired by the one in portal where we also want to ensure simple access to what user needs. We could maybe even create a separate argument which would accept an enumerated value which would be used for the ordering.

## Implementation details
- Primarily based on **weight** in descending order - users will most likely want to prioritise seeing the biggest score contributors.
- Secondarily based on **score** in the ascenading order - errors first.
- Tertiary ordering is based on **value** in descending order - usually bigger value means worse.
- Lastly the **alphabetical** order for the title.

**Comment by MishaSeredenkoPushBased** [comment]
Clarified requirements with @Tlacenka -
1. For MD, in Audits section keep separation by plugins. Sort audits inside, skip sorting by weight as it's not present.
  Same for stdout.
2. Keep categories at MD unsorted, in the order as defined at config. Sort groups and audits at the categories by the order defined in the description.
