### ISSUE TITLE
Remove `stdout` as format argument

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#247]
Extract of #191
The stdout format should be removed. We will always have some output, but some of it will be behind --verbose flag.

## Current behavior

The report summary is printed to stdout based on the `persist.format` value (set in `code-pushup.config.ts` or via `--persist.format` CLI argument).

The default `format` is `['json', 'stdout']`. It is not possible to skip `'json'` (we create it anyway regardless, it's needed for the upload). However, if a user wants to get a Markdown report as well, they can easily omit stdout without realizing it. E.g. if they add `--persist.format=md`, then it removes `stdout` because the array is replaced.

## Proposed change

We print the report summary regardless, and `stdout` will be removed from possible `format` values. If the user specifies `--persist.format=md`, then they will still see the report summary in the stdout.

The results of audits and categories are the most relevant information for the user when they run `collect`, and the report summary is minimal by design.

**Comment by vmasek** [comment]
Is there `stdout` used as of now in CLI? If not, please close the issue

**Comment by BioPhoton** [comment]
it is used

**Comment by BioPhoton** [comment]
Let's also add that the json file will get generated in any case.
