### ISSUE TITLE
Use `memfs`in all `plugin-eslint` tests

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#256]
related to #224

**Comment by Tlacenka** [comment]
I reviewed the usage of file system and it seems to be justified within the `plugin-eslint`:
- In `runner.integration.test.ts`, an actual runner output is created. To avoid issues with leftovers, the file is created in `node_modules` folder (comparable to `tmp`) and any errors inside the plugin would fail the test (no `catch` is present). 
- In `eslint-plugin.integration.test.ts`, only files from `fixtures` with the example repos are used as the root is set to `fixtures`, which is desired.
- Similarly, in `rules.unit.ts` the `cwd` is also set to rely on `fixtures` content only.
