### ISSUE TITLE
Change benchmark output from `ops/s` to `ms/run`

### ISSUE THREAD

**Issue by MishaSeredenkoPushBased** [code-pushup/cli#266]
It seems that current benchmark output with values at operations per second (ops/s) is not totally clear and perfect. Need to investigate other ways, for example translate the values into milliseconds per run (ms/run).

Here is an example of the current benchmark output:
<img width="798" alt="image" src="https://github.com/code-pushup/cli/assets/148336720/4cd80326-2efd-432c-93c8-4ef7c5a2863a">

**Comment by BioPhoton** [comment]
I would close it as no prio plus ops/sec is quite common compared to ms/run
