### ISSUE TITLE
Improve PR labeling

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#329]
As a Code PushUp contributor, I find it confusing when too many labels are applied on my PR.

I suggest adjusting the current PR labeler behaviour in the following way:
- [x] Only `packages/<package>/src/**` get the respective package label.
- [x] `tsconfig*.json`, `project.json`, `package.json`, `*eslintrc*` get a tooling label (to be created).
- [x] `vite.config*.ts` gets the 🔬 testing label.
- [x] `README.md` and `CHANGELOG.md` get the 📖 docs label.
- [x] `nx.json` and other root configuration files not matching the naming above would be under tooling as well.

These paths should be matched both for the root folder and for the package folder.

## Current behaviour example
In each package, only `project.json` has been changed.
![image](https://github.com/code-pushup/cli/assets/6306671/3e53a5b7-9012-402c-b176-f10853915870)

**Comment by matejchalk** [comment]
Happened to me too in #330 😅 Only changed ESLint configs.
