### ISSUE TITLE
[utils] integration test snapshot relies on `en-US` locale

### ISSUE THREAD

**Issue by LayZeeDK** [code-pushup/cli#374]
### What happened?

When I run integration tests for `@code-pushup/utils`, the snapshot for `report-to-stdout.integration.test.ts` only works when I set my operating system to the `en-US` locale.

This is caused by using `new Date().toString` instead of `new Date().toLocaleString('en-US, { /* (...) */ })` in the `reportToAboutSection` function. Alternatively, we could add a [development container](https://containers.dev/) to the project.

### What would you expect to happen?

Tests should work regardless of operating system locale to make it easier to contribute to the project.

### What steps did you take?

1. Change the regional formatting settings of your operating system to something other than `en-US`, in my case `da-DK`.
1. Run the `npx nx integration-test utils` command.
1. `report-to-md.integration.test.ts` fails

### What operation system are you on?

Windows

### Node version

18.19.0

### Relevant log output

```shell
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/lib/report-to-md.integration.test.ts > report-to-md > should contain all sections when using the fixture report
Error: Snapshot `report-to-md > should contain all sections when using the fixture report 1` mismatched

- Expected
+ Received

  ## About

- Report was created by [Code PushUp](https://github.com/flowup/quality-metrics-cli#readme) on Sat Jan 01 2000 00:00:00 GMT+0000 (Coordinated Universal Time).
+ Report was created by [Code PushUp](https://github.com/flowup/quality-metrics-cli#readme) on Sat Jan 01 2000 00:00:00 GMT+0000 (Koordineret universaltid).

❯ src/lib/report-to-md.integration.test.ts:28:22
     26|       `${commit.message} (${commit.hash.slice(0, 7)})`,
     27|     );
     28|     expect(mdReport).toMatchSnapshot();
       |                      ^
     29|   });
     30| });
```

**Comment by BioPhoton** [comment]
We could use a fixed format or different way to test it. This is less overhead than docker.

wdyt?

**Comment by LayZeeDK** [comment]
@BioPhoton 

Yes, if the Markdown report is always in English, we might as well explicitly use the `en-US` locale.

**Comment by matejchalk** [comment]
@LayZeeDK Thanks for the bug report :+1: 

It would be cool if there was some way to set a fixed locale in test setup, similar to how`process.env['TZ'] = 'UTC'` resolves any timezone mismatches :thinking: Unfortunately, I couldn't find any good solution for Node. Most people recommend `full-icu`, but that's overkill for our case.

So yeah, I think just specifying `'en-US'` locale explicitly in the source code is the simplest solution. As you say, all the outputs are English-only, so we don't need any complex I18N logic.

As for running tests in containers, I'd prefer not to go down that route. A fixed environment only solves the DX problem, but our users won't be running the CLI in some fixed environment. I'd prefer that we discover environment-specific bugs (like this one) from maintainers and contributors, i.e. as early as possible, when it's easiest to debug and fix.

**Comment by vmasek** [comment]
We'll fix this plus it would be nice to do research if this could be linted by some eslint plugin rules
