### ISSUE TITLE
Add hint to create categories in CLI reports

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#445]
### User story

As a user, I want to know about the option to create categories. Now that categories have been omitted from the basic setup docs and the report doesn't mention them if missing (see #437), a user is less likely to find out about this feature. 

### Acceptance criteria

- [ ] if categories are missing, generated reports should display a hint in their place
- [ ] hint should link to our docs on how to create categories

**Comment by BioPhoton** [comment]
ATM a hint is implemented. So IMO this could get closed.
Also, I a message independent of the report output is better than modifying the stdout of the report.

**Comment by matejchalk** [comment]
I think the remaing question is whether to include such a hint in the `report.md`, instead of just omtting the top section completely. What do you think?

**Comment by matejchalk** [comment]
OK, in that case this can indeed be closed.
