### ISSUE TITLE
Research static analysis plugin for C#

### ISSUE THREAD

**Issue by vmasek** [code-pushup/cli#450]
Investigate potential of integrating [Roslynator](https://github.com/dotnet/roslynator).

Desired output:

- [ ] Create a default list / preset of rules to be put into one or multiple categories
- [x] Connect the output of the analysis to the CLI models
- [x] Figure out how to detect enabled rules
- [x] Is there some plugin ecosystem? How do custom rules work?

Timebox: 2MDs

**Comment by matejchalk** [comment]
C# part researched and implemented by @PetrNavratil.
