### ISSUE TITLE
Display link to portal after upload

### ISSUE THREAD

**Issue by ChristopherPHolder** [code-pushup/cli#467]
### User story

As a user i would like to get the link to the report after i upload it.

After i run eg. `npx code-pushup`

I would like to get  a link to the newly generated report. 

![image](https://github.com/code-pushup/cli/assets/40126819/3719633f-0ee0-4e07-a4c5-9b5c19ab3593)

### Acceptance criteria

- [ ] Running the command `npx code-pushup` logs the url to the report at the end of the process if sucessful

**Comment by BioPhoton** [comment]
closed by #466
