### ISSUE TITLE
add commit property to report

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#471]
Useful for eg https://github.com/code-pushup/cli/blob/ef0c0da8ae591a37bf4e4298752901d6e3aa4b1e/packages/utils/src/lib/reports/utils.ts#L329 or the upload command https://github.com/code-pushup/cli/blob/a5068929fdaeb02fb2c73fbacd9eb37f3875df8f/packages/core/src/lib/upload.ts#L29

**Comment by vmasek** [comment]
Should be touched in https://github.com/code-pushup/portal/issues/268
