### ISSUE TITLE
TS config plugin

### ISSUE THREAD

**Issue by vmasek** [code-pushup/cli#483]
Placeholder issue WIP (feel free to enrich)

> As a user,
> I want a plugin that allows me to track violations of TypeScript (TS) compiler options that I specified to override my project's TS configuration,
> So that I can track and focus on adoption of strict options in future, improving code quality and consistency across my project.

Acceptance Criteria
- [ ] The plugin must allow users to define a set of rules or use predefined sets that map directly to TypeScript compiler options normally found in `tsconfig.json`.
- [ ] Automatically detect any code that violates the specified TypeScript compiler options. This includes checking for type safety, implicit any types, strict null checks, and other compiler options that can be enforced.
- [ ] Provide feedback in form of connected audits when violations are detected, highlighting the offending code, categorizing and suggesting possible fixes.

**Comment by BioPhoton** [comment]
Closed in favour of #901
