### ISSUE TITLE
Handling crashed plugins

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#497]
### User story

As a CP user, I wish to be able to understand what is going on, especially if one of the plugins crash. Currently, when a plugin crashes, the CLI continues. However, as the plugins are not filtered properly during scoring, the report is not created and I get a cryptic "invalid group reference" error message.

### Acceptance criteria

- [ ] Crashed plugins are filtered out during scoring and sorting, so that a valid report may be created.
- [x] The user is sufficiently informed about what went wrong in the failed plugin, e.g. by printing `stdout` and `stderr` (not just process code 1).

### Implementation details

Error message example:
![image](https://github.com/code-pushup/cli/assets/6306671/012b34fb-ce22-4f49-82cd-1daca44adda5)

**Comment by vmasek** [comment]
Conclusion: we want to let the "broken" run fail with no report collected as we want users to notice failed collection and don't want them to consume broken category scores.
