### ISSUE TITLE
Make getNxCoveragePaths more robust

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#536]
### User story

As an Nx user, I want to use the `getNxCoveragePaths` function to more easily configure `@code-pushup/coverage-plugin`. However, this function has too many assumptions built-in for it to be useful for a simple Nx + Jest setup.

### Acceptance criteria

- [x] do not require `coverageDirectory` (Jest) or `reportsDirectory` (Vitest) option to be set in `project.json`, also look for these properties in `jest.config.ts` and `vitest.config.ts` files (customizable via `config` option in `project.json`)
- [x] Vitest's paths are relative to project root, but Jest's paths are relative to workspace root - the `projectPath` property should only be set for Vitest, not Jest

**Comment by Tlacenka** [comment]
Related comment: https://github.com/code-pushup/cli/pull/604#discussion_r1555497103

**Comment by Tlacenka** [comment]
> Vitest's paths are relative to project root, but Jest's paths are relative to workspace root - the projectPath property should only be set for Vitest, not Jest

Additional information: For Cypress + nyc it is also relative to project root, not workspace root. However, Cypress can configure coverage from different sources so relying on `.nycrc.json` would not be wise.
