### ISSUE TITLE
Reduce number of lint rules in example app

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#558]
The `react-todos-app` is used in E2E tests for testing ESLint plugin among others. But since a lot of recommended ESLint rules are included, the test snapshots are quite large and therefore less readable. Most of the rules pass anyway, so they don't give much data variety. So we could remove some passing rules from the ESLint config without losing any test coverage.

**Comment by vmasek** [comment]
Wanted to have a look but I am not able to find the config in repo 🤔

**Comment by matejchalk** [comment]
There are a couple of places:
- [examples/react-todos-app/.eslintrc.js](https://github.com/code-pushup/cli/blob/main/examples/react-todos-app/.eslintrc.js) is used in E2E tests,
- [packages/plugin-eslint/mocks/fixtures/todos-app/.eslintrc.js](https://github.com/code-pushup/cli/blob/main/packages/plugin-eslint/mocks/fixtures/todos-app/.eslintrc.js) is used in plugin's integration tests

I believe the `extends: 'plugin:react/recommended'` pulls in most of the uninteresting rules, so my plan was to remove that. But haven't gotten round to it yet, there's always something higher prio that grabs my attention :sweat_smile:
