### ISSUE TITLE
Coverage has significantly decreased after Nx update

### ISSUE THREAD

**Issue by Tlacenka** [code-pushup/cli#560]
### What happened?

The code coverage score has decreased by 30 points after Nx update.

### What would you expect to happen?

The score would correctly update to the changes (no big fluctuation was expected).

### Code PushUp package version

0.25.4

### What operation system are you on?

Linux

### Node version

20.0.0

### Relevant information
- [commit link](https://github.com/code-pushup/cli/commit/b2c87eb716a84f82b5d59e7238ffcae7147f707a)
- [portal link](https://quality-metrics-staging.web.app/portal/code-pushup/cli/commit/b2c87eb716a84f82b5d59e7238ffcae7147f707a/dashboard)

The coverage is lower when running the plugin locally as well.
![image](https://github.com/code-pushup/cli/assets/6306671/90c438e7-59a9-41e1-b7be-f4f83c9391de)

**Comment by vmasek** [comment]
Check if related to #540

**Comment by Tlacenka** [comment]
I found out what the issue is.

We are providing both unit test and integration test results from the CLI to the plugin.
However, inside the plugin, there is no logic that would merge results if the same source file is found in multiple reports.
So, currently, the score is calculated from unit tests and integration tests as if they belonged to different projects. And issues are created for both separately.

What needs to happen is to merge results should a file be covered by different types of tests. And calculate the coverage score and issues only once all results are merged.
