### ISSUE TITLE
logs in coverage plugin are visible before execution

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#564]
### What happened?

When I setup the coverage plugin I get logs even if the plugin is not execution.

Logs:

```sh
💡 Gathering coverage from the following nx projects:
- plugin-lighthouse: unit-test
- plugin-coverage: unit-test
- plugin-eslint: unit-test
- nx-plugin: unit-test
- test-utils: unit-test
- examples-plugins: unit-test
- models: unit-test
- utils: unit-test
- core: unit-test
- cli: unit-test
- plugin-lighthouse: integration-test
- plugin-coverage: integration-test
- plugin-eslint: integration-test
- nx-plugin: integration-test
- examples-plugins: integration-test
- models: integration-test
```

### What would you expect to happen?

 should not see logs

### What steps did you take?

run collect

### What operation system are you on?

MacOS

**Comment by Tlacenka** [comment]
These logs were added as a feature of the Nx helper function `getNxCoveragePaths` in order to help the user see on which targets and on which projects the coverage will be measured.

If you remove this function from the code pushup config and add the paths manually or if you do not run coverage plugin at all, no logs will appear.

So please specify "should not see logs", otherwise this does not seem like a bug.

**Comment by BioPhoton** [comment]
Can you log it right before you execute? inside the runner?

**Comment by Tlacenka** [comment]
It is unfortunately not as easy as that. The helper is supposed to help provide locations of coverage files which are passed to the plugin in core config. What I can do though is to make the logs optional via a flag (and not display them by default). WDYT?

**Comment by BioPhoton** [comment]
Can we pass the data for the logs into the runner? 

I feel this is also misleading as I thought it executes before other plugins...

**Comment by Tlacenka** [comment]
Unfortunately, that is not easy atm. No logs inside plugins are visible unless a plugin fails which deserves a separate issue.

As a hotfix, I will move the logs under a flag which is turned off by default in #572 .

**Comment by matejchalk** [comment]
The solution is good enough for now, thanks 👍
