### ISSUE TITLE
Show `isBinary` icon report formats and stdout

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#592]
### User story

I configured a category as binary with the flag `isBinay` in `CategoryConfig`.

To test is I ran the collect command.

<img width="1038" alt="Screenshot 2024-03-29 at 23 07 36" src="https://github.com/code-pushup/cli/assets/10064416/82786e4f-0c59-4100-b2c0-352c066c367d">

### Acceptance criteria

- [ ] If a category is binary I would expect to get a visual feedback or influence on the rendered score.
  - [ ] In the **terminal** output in the **category overview** we show the checkmark/cross **before** the score number.  
   e.g. `✗ 87` or `✓ 87`.
  - [ ] In the **markdow report** in the **category overview** section we show the checkmark/cross **before** the score number.  
   e.g. `🟡 **87** ❌` or `🟡 **87** ✅`.
  - [ ] In the **markdow report** in the **category detail** section we show the checkmark/cross **after** the score number.  
 e.g. `Score:  **87** ❌` or `Score:  **87** ✅`.
   - [ ] In the **comparison report** in the **category overview** section we show the checkmark/cross **after** the score.  
 e.g. `🟡 **87** ❌` or `🟡 **87** ✅`.

### Implementation details

I suggest to already consider the new `targetScore` use naming that targets this future feature.

**`targetScore` icon logic suggestion**

```ts
export function targetScoreIcon(score: number, targetScore?: number): string {
  if (targetScore != null) {
    if (score >= targetScore) {
      return `✅`;
    }
    return `❌`;
  }
  return '';
}

```

---

## Examples

**Terminal Table**

```
┌─────────────────────────────────────────────────────────┬──────────┬──────────┐
│  Category                                               │  Score   │  Audits  │
├─────────────────────────────────────────────────────────┼──────────┼──────────┤
│  Bug prevention                                         │   ✓ 100  │     108  │
├─────────────────────────────────────────────────────────┼──────────┼──────────┤
│  Code style                                             │    ✗ 99  │     231  │
└─────────────────────────────────────────────────────────┴──────────┴──────────┘

```

<img width="649" alt="Screenshot 2024-06-23 at 21 16 06" src="https://github.com/code-pushup/cli/assets/10064416/cb3df47e-a905-42ad-9119-ea58664ef3f0">

---

**Report: Category Overview**

|🏷 Category|⭐ Score|🛡 Audits|
|:--|:--:|:--:|
| [Bug prevention](#bug-prevention) |🟢 **100** ✅|56|
| [Code style](#code-style) |🟢 **99** ❌|73|
| [Bug prevention](#bug-prevention) |🟢 **100 ✓**|56|
| [Code style](#code-style) |🟢 **99 ✗**|73|

---  

**Report: Category Details**

### Bug prevention

🟢 Score:  **100** ✅
- 🟩 [no-any](#no-any) (_eslint_) - **0**

### Code style

🟢 Score:  **99** ❌
- 🟩 [no-let) (_eslint_) - **0**

### Bug prevention

🟢 Score:  **100 ✓** 
- 🟩 [no-any](#no-any) (_eslint_) - **0**

### Code style

🟢 Score:  **99 ✗**
- 🟩 [no-let) (_eslint_) - **0**

---

**Comparison comment suggestion**

# Code PushUp

🤨 Code PushUp report has both **improvements and regressions** – compared target commit e214a030d91484a29071850ba811f5b43f1a3c16 with source commit 8d6dccbdf4799e97ce83b8909bacf96fc7ad8de8.

## 🏷️ Categories

|🏷️ Category|⭐ Current score|⭐ Previous score|🔄 Score change|
|:--|:--:|:--:|:--:|
| Bug prevention |🟡 **99** ✅|🟡 100 ❌|![↑ -4.2](https://img.shields.io/badge/%E2%86%91%20%2B4.2-green)|
| Code style |🟡 **98** ✅|🟡 99 ❌|![↑ +4.2](https://img.shields.io/badge/%E2%86%91%20%2B4.2-green)|
| Bug prevention |🟡 **100 ✓** |🟡 99 ✗|![↑ -4.2](https://img.shields.io/badge/%E2%86%91%20%2B4.2-green)|
| Code style |🟡 **98 ✗** |🟡 98 ✗|![↑ +4.2](https://img.shields.io/badge/%E2%86%91%20%2B4.2-green)|

</details>

**Comment by matejchalk** [comment]
Let's show the checkmark/cross before the score number, e.g. `❌ 88` or `✅ 100`.

| Category | Score | Audits |
|:--------|--------:|--------:|
| SEO | **93** | 15 |
| PWA | ❌ **88** | 9 | 
| PWA | ✅ **100** | 9 |
