### ISSUE TITLE
add CLI flag `--skipPlugins`

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#603]
### User story

As a developer sometimes I want to skip the execution of certain plugin. E.g. to save time.

ATM there is no way to do this but comment them out in the `code-pushup.config.ts`

### Acceptance criteria

- [ ] the CLI supports a terminal argument `skipPlugins` that is. used as string array that is `undefined` by default
- [ ] if `skipPlugins` is given exclude the provided plugins form the core config
- [ ] notify the user similar to `onlyPlugins`

**Comment by NachoVazquez** [comment]
@BioPhoton, I'll work on this if everyone is good with it!
