### ISSUE TITLE
nx plugin - `configuration` generator for standalone workspace layout

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#61]
The nx plugin should have a generator that is responsible for adding the `code-pushup.config.json` to a project in the workspace.

Todo:
- [ ] The project should get added over a CLI argument
- [ ] The project, if not given in the CLI arguments, should show up as select options in the CLI prompts
- [ ] In a standalone workspace layout a script should get added to the root `package.json` 
- [ ] In a common workspace layout (e.g. libs/apps) an error should get thrown that mentions that the feature will be implemented in the future.

**Comment by IKatsuba** [comment]
1. Why should we throw an error in common layout? Technically, standalone and common layouts are the same things. I'd like to write a warning message for all layouts. For example:
  ```
  @code-pushup/nx-plugin is not fully ready. For now, you have to run code-pushup with the following command:

  code-pushup <command> --config={projectRoot}/{fileName}

  In the future, we plan to add the Code PushUp executor.
  ```
  
2. Why should we add config to `package.json`? The separated config is more extendable.
