### ISSUE TITLE
docs: add package.json `description`

### ISSUE THREAD

**Issue by getlarge** [code-pushup/cli#632]
Minor detail, I know :) But it always looks better when the package has a description property.

<img width="589" alt="Screenshot 2024-04-17 at 08 19 05" src="https://github.com/code-pushup/cli/assets/15331923/f3899cff-08d4-4731-a334-6abad59a86f8">

**Comment by BioPhoton** [comment]
Seems like a very essential thing. @vmasek as you are assigned, could you take care about that pls.
