### ISSUE TITLE
Research older Node versions support

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#634]
This needs some research (timebox: 0.5 day):
- Let's figure which minimum Node version we should support.
- Let's check which newer Node APIs we're using (e.g. `structuredClone`) and what we can do to replace them (e.g. polyfill).
- Let's add Node version to GitHub Actions matrix and see how good other actions support is.

**Comment by matejchalk** [comment]
This needs some research:
- Let's figure which minimum Node version we should support.
- Let's check which newer Node APIs we're using and what we can do to replace them (e.g. polyfill).
- Let's add Node version to GitHub Actions matrix and see how good other actions support is.

**Comment by vmasek** [comment]
Should we set the minimal required Node version to LTS and not worry about this at least for now? I don't think it should be our priority to support old(er) nodejs if we do not even have mayor adoption of our tool in wild.

**Comment by vmasek** [comment]
Conclusion stick to the LTS and/or follow Nx minimal node version (which sticks to node LTS)
