### ISSUE TITLE
Implicit dependency on Chrome

### ISSUE THREAD

**Issue by getlarge** [code-pushup/cli#650]
The e2e tests implicitly depend on Chromium being available in the OS, and believe it or not, some people do not have the Chrome browser installed.

<img width="897" alt="Screenshot 2024-04-23 at 14 57 29" src="https://github.com/code-pushup/cli/assets/15331923/f7c1b05a-2d92-458b-879d-d4d9a4e5210a">

_Originally posted by @getlarge in https://github.com/code-pushup/cli/issues/639#issuecomment-2072229864_

**Comment by vmasek** [comment]
@BioPhoton please check if there is a way how to have chrome(ium) installed in package json dependency or other simple way how to have the e2e tests passed.

Otherwise writing it in contribution section in readme should be enough as we do not have other way how to run lighthouse.
