### ISSUE TITLE
Better error handling for yarn outdated

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#666]
When the lockfile is out-of-sync (solved by running `yarn install`), the error message isn't shown by the JS packages plugin, which instead crashes with a runtime error:

![image](https://github.com/code-pushup/cli/assets/34691111/c558c880-da64-43b9-b527-e2e2c0dc83a1)

**Comment by vmasek** [comment]
We also need to log actual error when the ESLint plugin fails
