### ISSUE TITLE
Replace chalk with ansis

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#738]
### User story

As a developer I want to use latest tools, minimize the dependency graph.

[chalk](https://github.com/chalk/chalk) has a couple op disadvantages:
- No dual module support
- large bundlesize
- many dependencies
- slow compared to other alternatives

Benchmarks of alternative options:

https://github.com/webdiscus/ansis#benchmark

### Acceptance criteria

- [ ] use [ansis](https://github.com/webdiscus/ansis)

### Implementation details

Relevant steps for our codebase:

1. Replacing chalk

```diff
Replace package name in import:

- import chalk from 'chalk'
+ import ansis, { red, green, cyan, black, ansi256, hex } from 'ansis';

```

2. Replace variable:

```diff

- chalk.red(text)
+ ansis.red(text)

```

3. Replace chains to nested calls:
    
    
```diff

- chalk.red.bold(text)
+ ansis.red(bold(text))

```

**Comment by webdiscus** [comment]
@BioPhoton 

you can replace chalk with [ansis](https://github.com/webdiscus/ansis).
Ansis is very small [![size](https://img.shields.io/bundlephobia/minzip/ansis)](https://bundlephobia.com/package/ansis) and fast. 
Ansis has all features of chalk and supports named import so your code will be more clean & clear:

```diff
- import chalk from 'chalk'
+ import ansis, {red, bold, underline, etc...} from 'ansis' 
```

Replace variable:
```diff
- chalk.red(text)
+ ansis.red(text)
// or
+ red(text)
```

Replace text:
```diff
- chalk.red('text')
+ ansis.red('text')
// or
+ red`text`
```

Replace chains:
```diff
- chalk.red.bold(text)
+ ansis.red.bold(text)
// or
+ red.bold(text)
// or
+ red`${bold(text)}`
```

**Comment by BioPhoton** [comment]
Thanks @webdiscus!! I will check it out right now.

What is the difference to picocolor?

**Comment by webdiscus** [comment]
@BioPhoton 
The difference to `picocolor` you can see in  the [features comparison](https://github.com/code-pushup/cli/issues/738#compare).

Picocolor is very primitive and doesn't supports runtimes like Bun, Deno, Next.JS.

**Comment by BioPhoton** [comment]
Convince, but your link is broken.

**Comment by webdiscus** [comment]
> Convince, but your link is broken.

sorry, the link above is fixed

**Comment by BioPhoton** [comment]
Description is updated, labeled correctly and moved into ready for refinement :)

**Comment by WuglyakBolgoink** [comment]
there is some problem (missed colors) with pico.

**Comment by BioPhoton** [comment]
I forgot to update the title 🙈

We switched to ansis. The title was the only description I forgot to update 🤷‍♂️

Sry for that ✌️
