### ISSUE TITLE
Npx command to setup default config

### ISSUE THREAD

**Issue by grizlizli** [code-pushup/cli#739]
### User story

As a developer, I would like to setup the CLI as easy as possible.

Running the command such as `npx code-pushup init` should create code-pushup.config.[ `ts` ~| `js` | `mjs`~ ] file.
init command should have arguments for file extension, default ts.

### Acceptance criteria

Running the above mentioned command should generate the config file in the project.

**Add package `create-cli`:**
- [x] create `create-cli` package to enable the `npx init @code-pushup/cli` command.
   The init command translates to `npm exec @code-pushup/create-cli`.  
   #779 
- [x] create init script that is able to reuse the `nx-plugin` logic

**Extend `nx-plugin`**
- ~extend the `ext` to accept a `ext` options to specify the file extension.~
- ~auto detect typescript and take `ts` if given. otherwise take `mjs` as extension.~

### Implementation details

Generate a config file in the root of the project.

**Comment by vmasek** [comment]
Please finalize the issue for refinement

**Comment by BioPhoton** [comment]
As this has quite a decent overlap with the nx generators we could do the following:

0. `npm init @code-pushup/cli` -> `npm exec @code-pushup/create-cli`
1. create a publishable package `create-cli`
2. inside use `nx g nx-plugin:config` 
2.1. I have to figure out how to execute the generator without a nx.json prelsent.

  @matejchalk WDYT?

**Comment by matejchalk** [comment]
> As this has quite a decent overlap with the nx generators we could do the following:
> 
> 0. `npm init @code-pushup/cli` -> `npm exec @code-pushup/create-cli`
> 1. create a publishable package `create-cli`
> 2. inside use `nx g  @code-pushup/nx-plugin:configuration`
>    2.1. I have to figure out how to execute the generator without a nx.json prelsent.

Yes! Having a `create-` package would give us compatibility with non-Nx codebases, since this package initializer format is supported by [NPM](https://docs.npmjs.com/cli/v10/commands/npm-init), [PNPM](https://pnpm.io/cli/create) and [Yarn 1](https://classic.yarnpkg.com/lang/en/docs/cli/create/).

**Comment by BioPhoton** [comment]
Updated issue and started work.
