### ISSUE TITLE
reduce dependencies

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#776]
### User story

For our current changelog flow we use conventional cimmits and the `conventional-changelog-angular@^7.0.0`package.
This has a dependency to `@angular-devkit/build-angular@^17`. 

### Acceptance criteria

- [ ] Check if it is even in use
- [ ] Get rid of angular as dependency by switching or re-creting the conventions

**Comment by vmasek** [comment]
Find out if we need the lib, how it is used
