### ISSUE TITLE
Prevent empty categories table in PR comments

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#819]
### What happened?

When only audits change, but categories, an empty categories table is displayed (only column headers).

![image](https://github.com/user-attachments/assets/612a4e84-302d-441c-9859-7dadd361543b)

### What would you expect to happen?

If all categories are unchanged, then the table shouldn't be shown, only the _All of 4 categories are unchanged_ message should be displayed

### What steps did you take?

Running Code PushUp GitHub Action in monorepo mode. Fixed a few lint errors, but not all, so there is no change to categories.

### Code PushUp package version

0.50.0

### What operation system are you on?

Linux

### Node version

20

**Comment by odoyhaha** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler
