### ISSUE TITLE
Skip perfect scores in stdout summary

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/cli#830]
Currently, the `collect`/`autorun` command lists every audit. When there are a lot of audits, this produces a very long output in CI ([full example here](https://github.com/code-pushup/portal/actions/runs/11107579633/job/30858494861?pr=503#step:5:82)).

```
ESLint audits

● Enforce a maximum number of lines per file                          6 warnings
● Enforce naming conventions for everything across a codebase         1 warning
● Require Promise-like statements to be handled appropriately         1 error
● "catch" clauses should do more than rethrow                         passed
● "switch" statements should not be nested                            passed
● "switch" statements should not have too many "case" clauses         passed
● A "while" loop should be used instead of a "for" loop               passed
● All branches in a conditional structure should not have exactly     passed
  the same implementation
● Boolean expressions should not be gratuitous                        passed
● Boolean literals should not be redundant                            passed
● Cognitive Complexity of functions should not be too high            passed
● Collapsible "if" statements should be merged                        passed
● Collection and array contents should be used                        passed
● Collection elements should not be replaced unconditionally          passed
● Collection sizes and array length comparisons should make sense     passed
```

We could truncate the output by compressing audits with perfect scores into a one line, which simply summariez how many there are:

```
ESLint audits

● Enforce a maximum number of lines per file                          6 warnings
● Enforce naming conventions for everything across a codebase         1 warning
● Require Promise-like statements to be handled appropriately         1 error
● ... 12 audits with perfect scores omitted for brevity ...
```

Optionally, we could show the full list when `--verbose` flag has been specified.

**Comment by BioPhoton** [comment]
Could we move the flag into persist options?
Verbose logging will print a lot of other infos too plus plugin internal things. This information is helpful for debugging but if you just want to see more audits maybe unexpected.

wdyt?

**Comment by hanna-skryl** [comment]
> Could we move the flag into persist options? 

I don't think this change should be tied to persistence. Whether or not audits with perfect scores are printed in the CLI output should not affect the content of generated reports. I see it as a CLI output readability enhancement. 

Will it be overkill to introduce a new global option, like `--showAllAudits`, defaulting to false?

**Comment by matejchalk** [comment]
I wouldn't add any extra options for this, it would be needlessly complicated and likely noone would use it. The vast majority of users will configure little to nothing. I suggested the `--verbose` flag because we already have it anyway and its a strong convention (unlike any custom flag we could add). And there is a general expectation that `--verbose` will result in many more logs than by default, so listing all audits seems like a reasonable side-effect to me.

I agree that persist options is the wrong place for such a flag anyway, I wouldn't consider stdout to be persistent. But I wouldn't add a new flag regardless.

At the end of the day, if the user wants to see all audits, the stdout summary isn't the best place to look for it. They have the full list of audits in `report.md` and `report.json` already, which is much more accessible than re-running everything with a different flag.

I would add that listing all audits in stdout when `--verbose` is _optional_ as far as I'm concerned. If perfect audits are always omitted regardless, then that's fine too. Basically, let's keep it simple (for us and for users).
