### ISSUE TITLE
Implement Lighthouse plugin

### ISSUE THREAD

**Issue by vmasek** [code-pushup/cli#90]
> As a user,
> I want a plugin that allows me to track performance degradations of any given URL,
> so that I can track and focus on adoption perf bottlenecks and opportunities to improve them.

**Acceptance Criteria:**. 
- [x] The plugin must allow users to define a single URL in the plugin options.
- [ ] Run lighthouse against that URL and get audit results in a CP report.
- [x] The plugin accepts all `CLIFlags` as well as `Config` for the official Lighthouse project
- [x] The plugin respects the following flags in relation to the CP data validation:
  - handle audits and groups filtering for `--onlyAudits` and `--onlyCategories`

**Comment by BioPhoton** [comment]
this is more of an epic an should get split
