### ISSUE TITLE
Enhance DX of plugin authors

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#92]
To improve the DX of plugin author's we should provide a couple of changes to the current data structure.

## Adoption of `RunnerConfig`

- [x] ~#227 => https://github.com/flowup/quality-metrics-cli/issues/227#issuecomment-1806756227~

This will make it easier to work with different cwd and config location settings.  
`npx ../../dist/packages/cli collect --config=../../packages/cli/test/plugin-progress-bar.config.mock.ts --outputDir=../../tmp` 

## Adoption of `RunnerConfig`

- [x] #228. 
   clodes by #229

If a transform function is provided,
the output of a plugin is piped through the provided transform function after we read the `plugin-output.josn`. 

```json
{
  plugins: [
    {
      outputPath: "out.json",
      transform: (data: Record<string, any>): PluginOutput => {
          return {
            //...
          }
      }
    }
  ]
}
```

## Adoption of `runner` type

- [x] #230

Would get executed inside the cli and its return value is directly used int the report.

```json
{
  plugins: [
    {
      runner: async (): void => {
         return // audit outputs
      }
    }
  ]
}
```

Implementation should be in different PRs.

**Comment by matejchalk** [comment]
@BioPhoton Can this be closed? All the referenced issues are done.
